import { APP_NAME } from "@/lib/constants";

interface ReportFooterProps {
  generatedBy?: string;
}

export function ReportFooter({ generatedBy = "System" }: ReportFooterProps) {
  return (
    <div className="mt-6 pt-4 border-t border-slate-200">
      <div className="flex items-center justify-between text-[10px] text-slate-400">
        <div>
          <p className="font-semibold text-slate-500">{APP_NAME}</p>
          <p>Financial Management System</p>
        </div>
        <div className="text-right">
          <p>Generated by: {generatedBy}</p>
          <p>{new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" })}</p>
        </div>
      </div>
    </div>
  );
}
